### ISSUE TITLE
Letters with diacritics not supported

### ISSUE THREAD

**Issue by Costava** [fengyuanchen/wordcounter#1]
Letters with diacritics (for example: á, ä, Ä, ó, ë, ñ) seem to be treated like spaces.

Input:
```
bär
```

Expected:
```
1> bär: 1
```

Actual:
```
1> b: 1
2> r: 1
```

**Comment by fengyuanchen** [comment]
RegExp `\w` does not match `á, ä, Ä, ó, ë, ñ`.

**Comment by MadLittleMods** [comment]
@fengyuanchen We can use `[a-z\u00E0-\u00FC]` from http://stackoverflow.com/a/11550799/796832

`\b[a-z\u00E0-\u00FC]+(-[a-z\u00E0-\u00FC]+)*\b`
 - https://github.com/fengyuanchen/wordcounter/blob/9064d75be229438c6be0d3662a91ab7b86f14f34/src/wordcounter.js#L56

**Comment by fengyuanchen** [comment]
Thank you. I will try it.

**Comment by fengyuanchen** [comment]
The v0.1.0 resolved this.
